name: Security Analysis

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0' # Exécution hebdomadaire le dimanche

jobs:
  bandit-scan:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install Bandit
      run: pip install bandit
      
    - name: Run Bandit (Security Linter)
      run: |
        # Scanner tous les fichiers Python en ignorant les environnements virtuels
        # Le niveau de log est ajusté pour signaler les vulnérabilités de moyenne et haute sévérité (-ll)
        bandit -r . -x ./venv,./.venv,./tests -ll -i
